spring.application.name=To_Do_App
server.port=8080
server.servlet.context-path=
server.error.include-message=always

# Database
spring.datasource.url=jdbc:mysql://localhost:3307/tododb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Other properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# File uploads
onedrive.access-token=
onedrive.upload-url=https://graph.microsoft.com/v1.0/me/drive/items/
file.upload-dir=./uploads